name: ha_leaf_status
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dartcarwings:
    git: https://gitlab.com/tobiaswkjeldsen/dartcarwings.git
  dartnissanconnectna:
    git: https://gitlab.com/tobiaswkjeldsen/dartnissanconnectna.git
  dartnissanconnect:
    git: https://gitlab.com/tobiaswkjeldsen/dartnissanconnect.git
  mqtt_client: ^9.3.1


dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
